### PR TITLE
Bump fprime to v3.4.1 (*see note)

### PR DESCRIPTION
**Pull request by ethancheez**
# Note!

Merge after [this PR](https://github.com/fprime-community/fprime-arduino/pull/19) is merged because the modified `Arduino.ArduinoTime` is needed

Also need to run `git submodule update --remote --recursive` after the `fprime-arduino` merge.

### CODE REVIEW

**Review by capsulecorplab — APPROVED** [review]
Along all the testing with the Teensy boards in #13, also ran a build of `fprime-baremetal-reference` in https://github.com/capsulecorplab/fprime-workspace-image/pull/43; LGTM

**Comment by capsulecorplab** [comment]
I spoke too soon; I'm getting a CMake error when attempting to re-generate build cache for the Teensy 3.2
Screenshot from 2023-12-13 16-04-59

**Comment by ethancheez** [comment]
Unable to reproduce. I see a `permission denied` on your screenshot. Does regenerating/rebuilding for `teensy40` and `teensy41` work?

**Comment by capsulecorplab** [comment]
> Unable to reproduce. I see a `permission denied` on your screenshot. Does regenerating/rebuilding for `teensy40` and `teensy41` work?

Same error with the `teensy41`, though I believe the error is actually with my environment; I changed the order in which arduino tools get installed in order to build the baremetal reference as part of the workspace image, but that seems to be causing the above `arduino-cli` error, since the previous image still works

**Comment by capsulecorplab** [comment]
Confirmed, it was my environment (see https://github.com/capsulecorplab/fprime-workspace-image/pull/43#issuecomment-1857227449). Not sure why changing the order in which `arduino-cli` was installed fixed the issue, but it works now

**Comment by capsulecorplab** [comment]
Sorry for the delayed response! I eventually resolved the aforementioned CMake error. It was an odd case where the error would persist if the baremetal reference was compiled as part of the environment. In any case, a pre-release of the environment that can build and flash the baremetal reference has been published here https://github.com/capsulecorplab/fprime-workspace-image/releases/tag/v3.4.0-alpha1.1.0. Will publish an official release once this PR is merged and semver tagged

**Pull request merged**
